---
#- debug: var=manageiq.api_url
#- debug: var=manageiq.api_token
#- name: Set the single vm tag URL
#  set_fact:
#    vm_tag_url: "{{ manageiq.api_url }}/api/{{ vm }}/tags"
#
#- debug: var=vm_tag_url
#- name: Set the tags for a single vm
#  uri:
#    url: "{{ vm_tag_url }}"
#    method: POST
#    body_format: json
#    body:
#      action: assign
#      resources : "{{ tags }}"
#    validate_certs: False
#    headers:
#      #X-Auth-Token: "{{ auth_token }}"
#      X-Auth-Token: "{{ manageiq.api_token }}"
#      Content-Type: "application/json"
#    status_code: 200
#  register: output
#
#- debug: var=output.json.results[0].success
#
#- name: Check if the VM was successfully tagged
#  fail: msg="{{output.json.results[0].message}}"
#  when: output.json.results[0].success == false

# Bulk tagging
#
- name: Set the bulk tag URL
  set_fact:
    # bulk_tag_url: "{{ manageiq.api_url }}/api/vms"
    bulk_tag_url: "{{ manageiq_api_url }}/api/vms"

- name: Set the array for bulk tagging
  set_fact:
    bulk_tags: "{{ bulk_tags|default([]) + [ { 'href': item.json.resources[0].href, 'tags': tags } ] }}"
  #with_items:
  #  - "api/{{ vm }}"
  #  - "api/vms/1000000000045"
  with_items: "{{ get_vms_ids.results }}"

- name: Set the bulk tag
  uri:
    url: "{{ bulk_tag_url }}"
    method: POST
    body_format: json
    body:
      action: assign_tags
      resources : "{{ bulk_tags }}"
    validate_certs: False
    headers:
      #X-Auth-Token: "{{ manageiq.api_token }}"
      X-Auth-Token: "{{ auth_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: output

- debug: var=output.json.results[0].success

- name: Check if the VM was successfully bulk tagged
  fail: msg="{{output.json.results[0].message}}"
  when: output.json.results[0].success == false
