- hosts: all
  gather_facts: no
#  become: true
  become_method: sudo
  become_user: root

  tasks:
  - debug:
      # var: hostvars 
      msg: "TEST_VARIABLE 1: {{ TEST_VAR_1 }}, TEST_VARIABLE 2: {{ TEST_VAR_2 }}"  
    register: shell_output
  
  - name: copy the output to a local file
    copy:
      content: "{{ shell_output }}"
      dest: "/tmp/ansi_variables.txt"
    delegate_to: localhost  
  
