---
- name: Creating empty file using Ansible playbook
  hosts: all
  #user: root
  #user: test
  become: yes
  tasks:
  - name: Ansible create file
    file:
      path: "/opt/test_ansible_file"
      state: touch
