---
- name: Install Docker
  hosts: all
  #become: yes

  tasks:
    - name: Install required packages (CentOS)
      package:
        name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install required packages (Ubuntu)
      package:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present
      when: ansible_os_family == 'Debian'
      
    - name: set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"
      when: ansible_os_family == 'RedHat'

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} stable
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
      when: ansible_os_family == 'RedHat'
      
    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true    
      when: ansible_os_family == 'RedHat'

    - name: Install Docker (Ubuntu)
      package:
        name: docker-ce
        state: present
      when: ansible_os_family == 'Debian'

    # - name: Add user to the docker group
      # user:
        # name: altech
        # groups: docker
        # append: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Install docker-compose
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'      

