---
- hosts: localhost
  connection: local
  vars_files:
    # Contains encrypted `secret_password` varibale using ansible-vault
    - passwords.yml
  tasks:
    - name: Show secret password from vault
      debug: msg="{{ secret_password }}"

