---
- name: Creating empty file using Ansible playbook
  hosts: all
  #user: root
  tasks:
  - name: Ansible create file
    file:
      path: "/opt/test_ansible_file"
      state: touch

  - name: Remove apt lock file
    file:
      state: absent
      path: "/var/lib/dpkg/lock-frontend"

  - name: Install Apache on Ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == 'Debian'

  - name: Install Apache on CentOS
    yum:
      name: httpd
      state: present
    when: ansible_os_family == 'RedHat'

  - name: Start Apache service
    service:
      name: httpd
      state: started
      enabled: false    
    when: ansible_os_family == 'RedHat'
      

 # - name: Start Apache service
 #   service:
  #    name: "{{ apache_service }}"
  #    state: started
  #    enabled: false
  #  vars:
  #    apache_service:
  #      Debian: apache2
   #     RedHat: httpd

  - name: Display info
    shell: echo "allokay..."
