---
- name: This is long running playbook
  hosts: all
  vars:
    timeout_default: "{{ timeout | default(3600) | int }}"
    timeout_divide_six: "{{ (timeout_default|int / 6)|int}}"
  tasks:
  - name: This is first task
    debug:
      msg="First message before sleep"

  - name: Sleep for "{{ timeout_divide_six }}" seconds and continue with play [sleeping for {{ timeout_default }} in total ]
    wait_for: 
      timeout="{{ item }}"
    delegate_to: localhost
    with_items:
      - "{{ timeout_divide_six }}"
      - "{{ timeout_divide_six }}"
      - "{{ timeout_divide_six }}"
      - "{{ timeout_divide_six }}"
      - "{{ timeout_divide_six }}"
      - "{{ timeout_divide_six }}"

  - name: This is third task
    debug:
        msg="Last message after sleep"
