---

# Defaults
manageiq_machine: "{{ manageiq_mach | default('localhost') }}"
manageiq: "https://{{ manageiq_machine }}"
#manageiq_api: "{{ manageiq }}/api"
manageiq_api_url: "{{ manageiq.api_url | default(manageiq) }}"
manageiq_user: "{{ manageiq_u | default('admin') }}"
manageiq_pass: "{{ manageiq_p | default('smartvm') }}"

manageiq_provider_auth: "{{ manageiq_api_url }}/api/auth"
manageiq_provider_url: "{{ manageiq_api_url }}/api/providers"
manageiq_provider_zone: "{{ manageiq_api_url }}/api/zone/2"
deploy_into_zone: default
manageiq_zones_url: "{{ manageiq_api_url }}/api/zones"
manageiq_zone_url: "{{ manageiq_api_url }}/api/zone"
manageiq_services_url: "{{ manageiq_api_url }}/api/services"
manageiq_vms_url: "{{ manageiq_api_url }}/api/vms"
# AWS specific
ec2_provider_name: "ec2_provider_{{ ec2_region }}"
ec2_provider_type: "ManageIQ::Providers::Amazon::CloudManager"
ec2_provider_credentials:
  userid: "{{ lookup('env', 'AWS_ACCESS_KEY') }}" 
  password: "{{ lookup('env', 'AWS_SECRET_KEY') }}" 
ec2_provider_zone:
  href: "{{ manageiq_provider_zone }}"
# Wait for provider refresh
retry_interval: 10
max_retries: 18
wait_seconds_before_refresh: 10


vm: "vms/1000000000029"
tags:
  - { category: "department", name: "qe"}
  - { category: "lifecycle", name: "retire_full"}


# Vars exposed by CFME to Tower
#add service
#manageiq.api_url
#manageiq.api_token

#manageiq.service
#manageiq.event_target

