- name: Hello Message
  debug: msg="Hello World!"

- name: Dump all variables
  template: src=./dump_all_variables.j2 dest=/var/tmp/touch_from_play_dumped_vars.txt

- name: Register content of templated file
  shell: cat /var/tmp/touch_from_play_dumped_vars.txt
  register: template
     
- name: Print content of templated file
  debug: msg="{{ template.stdout_lines }}"
